name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package

      - name: Read version from POM file
        id: version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: 'Release of version ${{ steps.version.outputs.version }}'
          draft: false
          prerelease: false

      - name: Upload artifact to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/elevenlabs-api/elevenlabs-api/target/elevenlabs-api-${{ steps.version.outputs.version }}-full.jar
          asset_name: elevenlabs-api-${{ steps.version.outputs.version }}-full.jar
          asset_content_type: application/java-archive
